New option REGPATH

diff --git a/OutlookFontPoke b/OutlookFontPoke
--- a/OutlookFontPoke
+++ b/OutlookFontPoke
@@ -15,7 +15,8 @@ TOOL_VERSION="2.1"
 ## Feedback: pbowden@microsoft.com
 
 # Constants
-REGISTRY="$HOME/Library/Group Containers/UBF8T346G9.Office/MicrosoftRegistrationDB.reg"
+REGISTRYPATH="$HOME/Library/Group Containers/UBF8T346G9.Office/MicrosoftRegistrationDB.reg"
+REGISTRY="$REGISTRYPATH/MicrosoftRegistrationDB.reg"
 OUTLOOKPATH="/Applications/Microsoft Outlook.app"
 SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
 
@@ -23,23 +24,24 @@ function ShowUsage {
 # Shows tool usage and parameters
 	echo $TOOL_NAME - $TOOL_VERSION
 	echo "Purpose: Sets the default compose and reply/forward fonts in Outlook 365/2021/2019/2016 for Mac"
-	echo "Usage: OutlookFontPoke [-dump] <font-name> <font-size> <font-color>"
+	echo "Usage: OutlookFontPoke [-dump] <font-name> <font-size> <font-color> <registry-path>"
 	echo "Example: OutlookFontPoke 'Helvetica' '11.0pt' 'gray'"
+	echo "Example: OutlookFontPoke 'Helvetica' '11.0pt' 'gray' '\$HOME/Library/Group Containers/UBF8T346G9.Office'"
 	echo
 	exit 0
 }
 
 function CheckRegistryExists {
 # Check if Registry exists
-if [ ! -e "$REGISTRY" ]; then
-	echo "WARNING: Registry DOES NOT exist at path $REGISTRY. Attempting to create..."
-	mkdir "$HOME/Library/Group Containers/UBF8T346G9.Office"
-	cp "$SCRIPTPATH/TemplateRegDB.reg" "$REGISTRY"
-	if [ "$?" != "0" ]; then
-		echo "ERROR: Registry could not be created."
-		exit 1
+	if [ ! -e "$REGISTRY" ]; then
+		echo "WARNING: Registry DOES NOT exist at path $REGISTRY. Attempting to create..."
+		mkdir -p "$REGISTRYPATH"
+		cp "$SCRIPTPATH/TemplateRegDB.reg" "$REGISTRY"
+		if [ "$?" != "0" ]; then
+			echo "ERROR: Registry could not be created."
+			exit 1
+		fi
 	fi
-fi
 }
 
 function CheckLaunchState {
@@ -125,9 +127,14 @@ else
 	FONTNAME="$1"
 	FONTSIZE="$2"
 	FONTCOLOR="$3"
+	REGPATH="$4"
 	
 	if [ "$FONTCOLOR" == '' ]; then
 		FONTCOLOR="windowtext"
+	fi
+	if [ "$REGPATH" != '' ]; then
+		REGISTRYPATH=$REGPATH
+		REGISTRY="$REGISTRYPATH/MicrosoftRegistrationDB.reg"
 	fi
 fi
 
